services:
  aqi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "8501:8501"
    env_file:
      - .env
    environment:
      AQI_API_URL: http://localhost:5000/api
    restart: unless-stopped
